### ISSUE TITLE
optitransv2 hindi doesnt display ंं  for .n

### ISSUE THREAD

**Issue by servant79** [indic-transliteration/m17n-db-indic#2]
the documentation at all places tells that
 .n  gives ं
but .n is giving me ।न
so i checked the script and found no entry for .n and hence this needs to be added it.

**Comment by vvasuki** [comment]
True. But I now wonder if this mapping is actually useful. What is your experience? You like this mapping I suppose?

**Comment by servant79** [comment]
It is more intuitive for me. I am currently editing 11000 lines hindi
scripture. I don't like using shift + m . .n is simpler

Regards
Vishal

**Comment by servant79** [comment]
Holding one key and pressing another key is complex operation compared to
pressing 2 keys in sequence
